config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  
  resources :tops do
  end
end

app/models/current_macs.rb
class CurrentMacs < ActiveRecord::Base
end

app/models/named_list.rb
class NamedList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @current_client_list = CurrentMacs.all
    @named_list = NamedList.all
    @client = NamedList.new
  end
  
  def create
    # todo ip,macのユニーク
    NamedList.create do |client|
      client.name = params[:named_list][:name]
      client.ip_address = params[:named_list][:ip_address]
      client.mac_address = params[:named_list][:mac_address]
    end
    redirect_to :tops
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MacWatcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tops/index.html.erb
Current List<BR/>
<TABLE>
  <TR>
      <% if 0 == (request.ip =~ /^192.168.([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$/) %>
        <TH>IP Address</TH>
        <TH>MAC Address</TH>
      <% end %>
      <TH>Client Name</TH>
  <TR>
  <% @current_client_list.each do |client| %>
    <TR>
      <% if 0 == (request.ip =~ /^192.168.([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$/) %>
	      <TD align="center"><%= client.ip_address %></TD>
        <TD align="center"><%= client.mac_address %></TD>
      <% end %>
      <TD align="center"><%= client.name %></TD>
    </TR>
  <% end %>
</TABLE><BR/>

<% if 0 == (request.ip =~ /^192.168.([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$/) %>
  Named List<BR/>
  <TABLE>
    <TR>
      <TH>Client Name</TH>
      <TH>MAC Address</TH>
      <TH>IP Address</TH>
    <TR>
    <% @named_list.each do |client| %>
      <TR>
        <TD align="center"><%= client.name %></TD>
        <TD align="center"><%= client.mac_address %></TD>
        <TD align="center"><%= client.ip_address %></TD>
      </TR>
    <% end %>
  </TABLE>
  
  <% #todo 削除機能 %>
  <%= form_for(@client, url: tops_path) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :mac_address %>
    <%= f.text_field :ip_address %>
    <%= f.submit %>
  <% end %>
<% end %>